services:
  # Main Interactive Web Application & REST API (Free Tier)
  - type: web
    name: mospi-airfare-index
    runtime: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt && playwright install --with-deps chromium
    startCommand: python airfare_index/live_fetcher/server.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 8000
